name: Auth WebDeploy

on:
    push:
        branches: [main, develop]

jobs:
    build:
        runs-on: ubuntu-latest
        environment:
            name: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
        steps:
            - uses: actions/checkout@v4.2.2
              with:
                  persist-credentials: false

            - name: Install
              run: npm i

            - name: Build
              run: npm run build

            - name: Set deploy directory
              env:
                  RELEASE_BRANCH: "refs/heads/main"
                  RELEASE_DIR: "/www/wwwroot/auth-qdsj/release"
                  DEV_BRANCH: "refs/heads/develop"
                  DEV_DIR: "/www/wwwroot/auth-qdsj/develop"
              run: |
                  # 根据分支设置部署路径
                  if [ "${{ github.ref }}" = "$RELEASE_BRANCH" ]; then
                    echo "DEPLOY_DIR=$RELEASE_DIR" >> $GITHUB_ENV
                  elif [ "${{ github.ref }}" = "$DEV_BRANCH" ]; then
                    echo "DEPLOY_DIR=$DEV_DIR" >> $GITHUB_ENV
                  fi
            # 通过 SSH 在服务器上部署
            - name: Deploy to Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER_NAME }}
                  key: ${{ secrets.SERVER_KEY }}
                  script: |
                      TIMESTAMP=$(date +%Y%m%d_%H%M%S)
                      DEPLOY_DIR_PRE="${DEPLOY_DIR}"
                      DEPLOY_DIR="${DEPLOY_DIR}/${TIMESTAMP}"

                      mkdir -p ${DEPLOY_DIR}
                      scp -r dist/* $DEPLOY_USER@$DEPLOY_HOST:${DEPLOY_DIR}/
                      ln -sfn ${DEPLOY_DIR} ${DEPLOY_DIR_PRE}/current
